# Channel Configuration File
# Contains channel-specific settings and references which bot to use
bot_name: "mybot"  # References which bot's auth file to use
channel: "channel1"  # The Twitch channel name

# Channel-specific settings
data_path: "/app/data/channel1"  # Channel-specific data path

# Command-specific configurations
commands:
  # Queue management
  queue:
    # Maximum number of users allowed in queue
    max_size: 100
    
    # Default position for move command
    default_position: 1
    
    # Number of users to pop by default
    default_pop_count: 1

  # Cooldown settings (in seconds)
  cooldowns:
    default: 5
    moderator: 2
    vip: 3

  # Individual command settings
  - name: "!command1"
    description: "Channel specific command"
  - name: "!command2"
    description: "Another channel command" 