# Bot Authentication File
# Contains ONLY bot credentials and API keys
bot_name: "mybot"
oauth: "oauth:your_oauth_token"
client_id: "your_client_id"
client_secret: "your_client_secret"

# API Keys for various services
apis:
  twitch:
    client_id: "your_twitch_client_id"
    client_secret: "your_twitch_client_secret"
  openai:
    api_key: "your_openai_api_key"
  riot:
    api_key: "your_riot_api_key" 