# Twitch Configuration Template
# Copy this file to create a new channel's secrets file:
# Example: cp secrets.template.yaml pbuckles_secrets.yaml
# Then update the values below for your channel

twitch:
  # Your Twitch Bot's OAuth token
  # Get it from: https://twitchapps.com/tmi/
  bot_token: "oauth:your_bot_token_here"
  
  # Your Twitch application client ID
  # Get it from: https://dev.twitch.tv/console/apps
  client_id: "your_client_id_here"
  
  # Your Twitch application client secret
  client_secret: "your_client_secret_here"

  # Bot account username (lowercase)
  bot_username: "YourBotName"

  # Channel to join (lowercase)
  channel: "channel_name"

  # Data path for channel-specific storage (optional)
  # Defaults to /app/data/channel_name if not specified
  data_path: "/app/data"

# Command-specific configurations
commands:
  # Queue management
  queue:
    # Maximum number of users allowed in queue
    max_size: 100
    
    # Default position for move command
    default_position: 1
    
    # Number of users to pop by default
    default_pop_count: 1

  # Cooldown settings (in seconds)
  cooldowns:
    default: 5
    moderator: 2
    vip: 3

# Optional: Additional API keys
apis:
  # Add any additional API keys here
  example_api_key: ""  # Add your API key here if needed 