# Twitch Configuration
twitch:
  # Your Twitch Bot's OAuth token
  # Get it from: https://twitchapps.com/tmi/
  bot_token: "oauth:your_token_here"
  
  # Your Twitch application client ID
  # Get it from: https://dev.twitch.tv/console/apps
  client_id: "your_client_id_here"
  
  # Your Twitch application client secret
  client_secret: "your_client_secret_here"

  # Bot account username (lowercase)
  bot_username: "your_bot_username"

  # Channel to join (lowercase)
  channel: "your_channel_name"

# Optional: Additional API keys
apis:
  # Add any additional API keys here
  example_api_key: "your_api_key_here" 